services:
  - type: web
    name: helpdesk-atendify-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && node prisma/setup-triggers.js && (node prisma/seed.js || true) && node src/app.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: NODE_ENV
        value: production
