/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitasRouteImport } from './routes/visitas'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TamanhosRouteImport } from './routes/tamanhos'
import { Route as SacoleiraRouteImport } from './routes/sacoleira'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as FornecedorRouteImport } from './routes/fornecedor'
import { Route as FinalizadorasRouteImport } from './routes/finalizadoras'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CoresRouteImport } from './routes/cores'
import { Route as ComissaoRouteImport } from './routes/comissao'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CargosRouteImport } from './routes/cargos'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VisitasRoute = VisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TamanhosRoute = TamanhosRouteImport.update({
  id: '/tamanhos',
  path: '/tamanhos',
  getParentRoute: () => rootRouteImport,
} as any)
const SacoleiraRoute = SacoleiraRouteImport.update({
  id: '/sacoleira',
  path: '/sacoleira',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorRoute = FornecedorRouteImport.update({
  id: '/fornecedor',
  path: '/fornecedor',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalizadorasRoute = FinalizadorasRouteImport.update({
  id: '/finalizadoras',
  path: '/finalizadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CoresRoute = CoresRouteImport.update({
  id: '/cores',
  path: '/cores',
  getParentRoute: () => rootRouteImport,
} as any)
const ComissaoRoute = ComissaoRouteImport.update({
  id: '/comissao',
  path: '/comissao',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CargosRoute = CargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/cargos': typeof CargosRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/comissao': typeof ComissaoRoute
  '/cores': typeof CoresRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/finalizadoras': typeof FinalizadorasRoute
  '/fornecedor': typeof FornecedorRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/sacoleira': typeof SacoleiraRoute
  '/tamanhos': typeof TamanhosRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas': typeof VendasRoute
  '/visitas': typeof VisitasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/cargos': typeof CargosRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/comissao': typeof ComissaoRoute
  '/cores': typeof CoresRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/finalizadoras': typeof FinalizadorasRoute
  '/fornecedor': typeof FornecedorRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/sacoleira': typeof SacoleiraRoute
  '/tamanhos': typeof TamanhosRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas': typeof VendasRoute
  '/visitas': typeof VisitasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/cargos': typeof CargosRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/comissao': typeof ComissaoRoute
  '/cores': typeof CoresRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/finalizadoras': typeof FinalizadorasRoute
  '/fornecedor': typeof FornecedorRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/sacoleira': typeof SacoleiraRoute
  '/tamanhos': typeof TamanhosRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas': typeof VendasRoute
  '/visitas': typeof VisitasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auditoria'
    | '/cargos'
    | '/categorias'
    | '/clientes'
    | '/comissao'
    | '/cores'
    | '/crm'
    | '/dashboard'
    | '/finalizadoras'
    | '/fornecedor'
    | '/produtos'
    | '/relatorios'
    | '/sacoleira'
    | '/tamanhos'
    | '/usuarios'
    | '/vendas'
    | '/visitas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auditoria'
    | '/cargos'
    | '/categorias'
    | '/clientes'
    | '/comissao'
    | '/cores'
    | '/crm'
    | '/dashboard'
    | '/finalizadoras'
    | '/fornecedor'
    | '/produtos'
    | '/relatorios'
    | '/sacoleira'
    | '/tamanhos'
    | '/usuarios'
    | '/vendas'
    | '/visitas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auditoria'
    | '/cargos'
    | '/categorias'
    | '/clientes'
    | '/comissao'
    | '/cores'
    | '/crm'
    | '/dashboard'
    | '/finalizadoras'
    | '/fornecedor'
    | '/produtos'
    | '/relatorios'
    | '/sacoleira'
    | '/tamanhos'
    | '/usuarios'
    | '/vendas'
    | '/visitas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CargosRoute: typeof CargosRoute
  CategoriasRoute: typeof CategoriasRoute
  ClientesRoute: typeof ClientesRoute
  ComissaoRoute: typeof ComissaoRoute
  CoresRoute: typeof CoresRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  FinalizadorasRoute: typeof FinalizadorasRoute
  FornecedorRoute: typeof FornecedorRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SacoleiraRoute: typeof SacoleiraRoute
  TamanhosRoute: typeof TamanhosRoute
  UsuariosRoute: typeof UsuariosRoute
  VendasRoute: typeof VendasRoute
  VisitasRoute: typeof VisitasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitas': {
      id: '/visitas'
      path: '/visitas'
      fullPath: '/visitas'
      preLoaderRoute: typeof VisitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tamanhos': {
      id: '/tamanhos'
      path: '/tamanhos'
      fullPath: '/tamanhos'
      preLoaderRoute: typeof TamanhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sacoleira': {
      id: '/sacoleira'
      path: '/sacoleira'
      fullPath: '/sacoleira'
      preLoaderRoute: typeof SacoleiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor': {
      id: '/fornecedor'
      path: '/fornecedor'
      fullPath: '/fornecedor'
      preLoaderRoute: typeof FornecedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finalizadoras': {
      id: '/finalizadoras'
      path: '/finalizadoras'
      fullPath: '/finalizadoras'
      preLoaderRoute: typeof FinalizadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cores': {
      id: '/cores'
      path: '/cores'
      fullPath: '/cores'
      preLoaderRoute: typeof CoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comissao': {
      id: '/comissao'
      path: '/comissao'
      fullPath: '/comissao'
      preLoaderRoute: typeof ComissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargos': {
      id: '/cargos'
      path: '/cargos'
      fullPath: '/cargos'
      preLoaderRoute: typeof CargosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditoriaRoute: AuditoriaRoute,
  CargosRoute: CargosRoute,
  CategoriasRoute: CategoriasRoute,
  ClientesRoute: ClientesRoute,
  ComissaoRoute: ComissaoRoute,
  CoresRoute: CoresRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  FinalizadorasRoute: FinalizadorasRoute,
  FornecedorRoute: FornecedorRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  SacoleiraRoute: SacoleiraRoute,
  TamanhosRoute: TamanhosRoute,
  UsuariosRoute: UsuariosRoute,
  VendasRoute: VendasRoute,
  VisitasRoute: VisitasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
